
services:
  agentic-rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_rag
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app/app
      - ./requirements.txt:/usr/src/app/requirements.txt
    ports:
      - "8000:8000"
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
      - qdrant
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 & \
      mlflow server --host 0.0.0.0 --port 5000"
    env_file:
    - .env

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  redis_data:
  qdrant_data:
