version: '3.9'

services:
  agentic-rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_rag
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
      - qdrant
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow_server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: mlflow server
    depends_on:
      - mongodb
      - redis
      - qdrant
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
      
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  redis_data:
  qdrant_data:
